import type { CampaignTrack, GameLevel } from './campaign'

export interface GuidedCampaign extends CampaignTrack {
  readonly difficulty: string
  readonly completionInsight: string
}

const world = (id: string, atoms: string, x: number, y: number) => ({ id, atoms, position: { x, y } })
const splitWorlds = () => [world('w0', '', 80, 135), world('w1', '', 335, 55), world('w2', '', 335, 215)]
const splitEdges = [{ from: 'w0', to: 'w1' }, { from: 'w0', to: 'w2' }]

export const countermodelHunter: GuidedCampaign = {
  id: 'countermodel-hunter',
  title: 'Countermodel Hunter',
  description: 'Construct small Kripke models that refute invalid modal claims.',
  difficulty: 'Intermediate',
  completionInsight: 'Modal countermodels often assign different semantic roles to different successors: a witness, a counterexample, or a branch that creates vacuous truth.',
  levels: [
    { id: 'hunter-empty-successors', chapter: 'Countermodel Hunter', title: 'Empty Successors', concept: 'Vacuous box', learningObjective: 'Use vacuous truth to construct the smallest countermodel.', briefing: 'A conditional is false only when its antecedent is true and its consequent is false. Construct a model in which □p is true at w0 while p itself is false there.', instruction: 'Make □p → p false at w0 by changing only the valuation.', formula: 'box p -> p', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: [world('w0', 'p', 180, 130)], edges: [], constraints: { minimumWorlds: 1, maximumWorlds: 1, maximumEdges: 0 }, editable: ['valuations'], hints: ['To falsify A → B, make A true and B false.', 'With no successors, □p is already true at w0.', 'Remove p from the valuation of w0.'], successDebrief: 'The implication is false because □p is vacuously true while p is false at w0. This is the smallest possible countermodel.', targetAnalysis: ['To make A → B false: A must be true. B must be false.'], referenceSolution: { worlds: [world('w0', '', 180, 130)], edges: [], evaluationWorld: 'w0' } },
    { id: 'hunter-witness-counterexample', chapter: 'Countermodel Hunter', title: 'Witness and Counterexample', concept: 'Split modal roles', learningObjective: 'Use one successor as a diamond witness and another as a box counterexample.', briefing: 'Possibility needs one successful successor. Necessity fails because of one unsuccessful successor. These roles can be played by different worlds.', instruction: 'Make ◇p true and □p false at w0.', formula: 'diamond p -> box p', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: splitWorlds(), edges: splitEdges, constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredEdges: splitEdges }, editable: ['valuations'], hints: ['Make the antecedent true and the consequent false.', 'Use one successor as a p-witness and the other as a non-p counterexample.', 'Put p at exactly one of w1 and w2.'], successDebrief: 'One successor witnesses possibility, while another refutes necessity. A diamond and a box quantify over the same successors in different ways.', targetAnalysis: ['To make A → B false: A must be true. B must be false.'], referenceSolution: { worlds: [world('w0', '', 80, 135), world('w1', 'p', 335, 55), world('w2', '', 335, 215)], edges: splitEdges, evaluationWorld: 'w0' } },
    { id: 'hunter-split-disjunction', chapter: 'Countermodel Hunter', title: 'Split Disjunction', concept: 'Universal distribution over disjunction', learningObjective: 'Separate p and q between successors while every successor satisfies p ∨ q.', briefing: '□(p ∨ q) requires every successor to satisfy at least one disjunct. It does not require the same disjunct in every successor.', instruction: 'Make □(p ∨ q) true while making both □p and □q false at w0.', formula: 'box (p | q) -> (box p | box q)', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: splitWorlds(), edges: splitEdges, constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredEdges: splitEdges }, editable: ['valuations'], prediction: { kind: 'truth', prompt: 'For □(p ∨ q) to be true, must the same disjunct be true at every successor?' }, hints: ['To falsify the conclusion, both □p and □q must be false.', 'One successor must fail p, and one successor must fail q.', 'Put only p at one successor and only q at the other.'], successDebrief: 'Every successor satisfies p ∨ q, but the successful disjunct varies between successors. Universal quantification does not distribute over disjunction in this direction.', targetAnalysis: ['To make A → B false: A must be true. B must be false.'], referenceSolution: { worlds: [world('w0', '', 80, 135), world('w1', 'p', 335, 55), world('w2', 'q', 335, 215)], edges: splitEdges, evaluationWorld: 'w0' } },
    { id: 'hunter-separate-witnesses', chapter: 'Countermodel Hunter', title: 'Separate Witnesses', concept: 'Independent existential witnesses', learningObjective: 'Use different successors to witness two diamonds without a shared witness.', briefing: 'A witness for p need not be the same world as a witness for q.', instruction: 'Make ◇p and ◇q true while keeping ◇(p ∧ q) false.', formula: '(diamond p & diamond q) -> diamond (p & q)', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: splitWorlds(), edges: splitEdges, constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredEdges: splitEdges }, editable: ['valuations'], hints: ['The two diamonds do not have to use the same witness.', 'Use one successor for p and another for q.', 'Ensure that no accessible world contains both atoms.'], successDebrief: 'The antecedent uses two separate witnesses. The conclusion requires one shared witness, which this model lacks.', targetAnalysis: ['To make A → B false: A must be true. B must be false.'], referenceSolution: { worlds: [world('w0', '', 80, 135), world('w1', 'p', 335, 55), world('w2', 'q', 335, 215)], edges: splitEdges, evaluationWorld: 'w0' } },
    { id: 'hunter-converse-k', chapter: 'Countermodel Hunter', title: 'The Converse of K', concept: 'Invalid converse of axiom K', learningObjective: 'Refute the converse of K by separating an outer implication from an inner boxed implication.', briefing: 'The usual K direction is valid. The reverse direction is not. Construct a model showing why.', instruction: 'Make □p → □q true while making □(p → q) false at w0.', formula: '(box p -> box q) -> box (p -> q)', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: splitWorlds(), edges: splitEdges, constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredEdges: splitEdges }, editable: ['valuations'], prediction: { kind: 'model-choice', prompt: 'Which strategy can make □p → □q true while leaving room to falsify □(p → q)?', expectedChoice: 'A', modelChoices: [{ id: 'A', evaluationWorld: 'w0', worlds: [{ id: 'w0', atoms: '' }, { id: 'w1', atoms: 'p' }, { id: 'w2', atoms: '' }], edges: splitEdges }, { id: 'B', evaluationWorld: 'w0', worlds: [{ id: 'w0', atoms: '' }, { id: 'w1', atoms: 'p q' }, { id: 'w2', atoms: 'p q' }], edges: splitEdges }] }, hints: ['The outer implication is false only when its left side is true and its right side is false.', 'Make □p → □q true because □p is false.', 'Use one successor with p true and q false, and another with p false.'], successDebrief: 'The left side is true because □p is false. The right side is false because one successor makes p → q false. This demonstrates why the converse of K is invalid.', targetAnalysis: ['To make A → B false: A must be true. B must be false.'], referenceSolution: { worlds: [world('w0', '', 80, 135), world('w1', 'p', 335, 55), world('w2', '', 335, 215)], edges: splitEdges, evaluationWorld: 'w0' } },
    { id: 'hunter-modal-order', chapter: 'Countermodel Hunter', title: 'Modal Order', concept: 'Different modal quantifier orders', learningObjective: 'Separate ◇□p from □◇p using two looped branches.', briefing: 'One successor may make □p true, while another successor makes ◇p false. Use those two branches to separate the formulas.', instruction: 'Make ◇□p true and □◇p false at w0 by changing only the valuation.', formula: 'diamond box p -> box diamond p', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: splitWorlds(), edges: [...splitEdges, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }], constraints: { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 4, maximumEdges: 4, requiredEdges: [...splitEdges, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }] }, editable: ['valuations'], hints: ['The diamond on the left needs one successor satisfying □p.', 'The box on the right fails if one successor falsifies ◇p.', 'Put p at one looped successor and leave it false at the other.'], successDebrief: 'One branch supplies a successor where p is necessary. The other supplies a successor where p is not possible, so the modal orders diverge.', targetAnalysis: ['To make A → B false: A must be true. B must be false.'], referenceSolution: { worlds: [world('w0', '', 80, 135), world('w1', 'p', 335, 55), world('w2', '', 335, 215)], edges: [...splitEdges, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }], evaluationWorld: 'w0' } },
    { id: 'hunter-final-investigation', chapter: 'Countermodel Hunter', title: 'Final Investigation', concept: 'Open countermodel construction', learningObjective: 'Construct a countermodel combining box, diamond, and implication.', briefing: 'Every accessible p-world may satisfy q, while a different accessible world still falsifies q. Construct a countermodel.', instruction: 'Construct a countermodel to □(p → q) → (◇p → □q).', formula: 'box (p -> q) -> (diamond p -> box q)', scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds: splitWorlds(), edges: [], constraints: { minimumWorlds: 3, maximumWorlds: 3, maximumEdges: 2, forbiddenEdges: [{ from: 'w0', to: 'w0' }] }, bonusConstraints: { minimumEdges: 2, maximumEdges: 2, requiredEdges: splitEdges }, editable: ['valuations', 'edges'], hints: ['To falsify the outer implication, keep □(p → q) true and make ◇p → □q false.', 'The inner implication is false when ◇p is true and □q is false.', 'Use one successor with p and q, and another with neither p nor q.'], successDebrief: 'Every accessible p-world satisfies q, so □(p → q) is true. One p-witness does not force q at every successor: another successor falsifies □q.', targetAnalysis: ['To make A → B false: A must be true. B must be false.', 'The result is a countermodel on an unrestricted finite K-frame, not a claim that the formula is false in every model.'], referenceSolution: { worlds: [world('w0', '', 80, 135), world('w1', 'p q', 335, 55), world('w2', '', 335, 215)], edges: splitEdges, evaluationWorld: 'w0' } },
  ],
}

const frame = (worlds: readonly ReturnType<typeof world>[], edges: readonly { readonly from: string; readonly to: string }[], id: string, title: string, instruction: string, constraints: NonNullable<GameLevel['constraints']>, referenceSolution: NonNullable<GameLevel['referenceSolution']>, hints: readonly [string, string, string], briefing: string, successDebrief: string): GameLevel => ({ id, chapter: 'Frame Architect', title, concept: 'Accessibility-frame properties', learningObjective: instruction, briefing, instruction, objectiveKind: 'construction', structuralObjective: {}, evaluationWorld: 'w0', worlds, edges, constraints, editable: ['edges'], frameRules: { reflexive: 'validate', serial: 'validate', symmetric: 'validate', transitive: 'validate', euclidean: 'validate' }, hints, successDebrief, targetAnalysis: ['The relational constraints are the complete construction objective.', 'Validate checks the explicit relation. it does not add missing relations.'], referenceSolution })

const frameArchitect: GuidedCampaign = {
  id: 'frame-architect', title: 'Frame Architect', description: 'Design accessibility relations with precisely controlled structural properties.', difficulty: 'Intermediate', completionInsight: 'Frame properties are independent constraints on one relation. Modal frame classes become clearer when examples deliberately satisfy some properties while violating others.',
  levels: [
    frame([world('w0', '', 70, 130), world('w1', '', 300, 55), world('w2', '', 300, 205)], [{ from: 'w0', to: 'w0' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w2' }], 'architect-reflexive-repair', 'Reflexive Repair', 'Repair the frame so that it is reflexive. Preserve every existing edge and add as few new edges as possible.', { minimumWorlds: 3, maximumWorlds: 3, maximumEdges: 5, requiredEdges: [{ from: 'w0', to: 'w0' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w2' }], requiredProperties: ['reflexive'] }, { worlds: [world('w0', '', 70, 130), world('w1', '', 300, 55), world('w2', '', 300, 205)], edges: [{ from: 'w0', to: 'w0' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w2' }], evaluationWorld: 'w0' }, ['Reflexivity requires every world to have a self-loop.', 'Check the worlds one by one rather than following longer paths.', 'w1 is the only world missing an edge to itself.'], 'Reflexivity is checked locally at every world.', 'Every world now accesses itself. Reflexivity does not depend on edges between different worlds.'),
    frame([world('w0', '', 100, 130), world('w1', '', 390, 130)], [], 'architect-serial-not-reflexive', 'Serial Without Reflexivity', 'Construct a serial frame that is not reflexive.', { minimumWorlds: 2, maximumWorlds: 2, minimumEdges: 2, maximumEdges: 2, requiredProperties: ['serial'], forbiddenProperties: ['reflexive'] }, { worlds: [world('w0', '', 100, 130), world('w1', '', 390, 130)], edges: [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w0' }], evaluationWorld: 'w0' }, ['Seriality only requires at least one successor for each world.', 'A successor may be a different world.', 'Give each world an outgoing edge while leaving a self-loop absent.'], 'Seriality does not require self-accessibility.', 'Every world has a successor, but neither world needs a self-loop. Seriality does not imply reflexivity.'),
    frame([world('w0', '', 70, 130), world('w1', '', 300, 55), world('w2', '', 300, 205)], [{ from: 'w0', to: 'w0' }, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w0' }, { from: 'w1', to: 'w2' }], 'architect-symmetric-not-transitive', 'Symmetric but Not Transitive', 'Make the relation reflexive and symmetric while keeping it non-transitive.', { minimumWorlds: 3, maximumWorlds: 3, maximumEdges: 7, requiredEdges: [{ from: 'w0', to: 'w0' }, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w0' }, { from: 'w1', to: 'w2' }], requiredProperties: ['reflexive', 'symmetric'], forbiddenProperties: ['transitive'] }, { worlds: [world('w0', '', 70, 130), world('w1', '', 300, 55), world('w2', '', 300, 205)], edges: [{ from: 'w0', to: 'w0' }, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w0' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w1' }], evaluationWorld: 'w0' }, ['Symmetry requires every edge to have its reverse.', 'Preserve a two-step path whose shortcut is absent.', 'Add w2 → w1, but do not connect w0 directly with w2.'], 'A symmetric relation may still omit a transitive shortcut.', 'The path w0 → w1 → w2 lacks w0 → w2, so transitivity fails even though the relation is reflexive and symmetric.'),
    frame([world('w0', '', 100, 130), world('w1', '', 390, 130)], [{ from: 'w0', to: 'w1' }], 'architect-transitive-serial-not-reflexive', 'Transitive and Serial, Not Reflexive', 'Add the smallest number of edges so the frame becomes serial and transitive, but remains non-reflexive.', { minimumWorlds: 2, maximumWorlds: 2, maximumEdges: 2, requiredEdges: [{ from: 'w0', to: 'w1' }], requiredProperties: ['serial', 'transitive'], forbiddenProperties: ['reflexive'] }, { worlds: [world('w0', '', 100, 130), world('w1', '', 390, 130)], edges: [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }], evaluationWorld: 'w0' }, ['The only world without a successor is w1.', 'The added edge must not create a missing transitive shortcut.', 'Give w1 a self-loop.'], 'Transitivity closes paths. it does not demand every self-loop.', 'The frame is serial and transitive, but w0 does not access itself. Transitivity does not imply reflexivity.'),
    frame([world('w0', '', 70, 130), world('w1', '', 300, 55), world('w2', '', 300, 205)], [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w1' }], 'architect-euclidean-not-transitive', 'Euclidean but Not Transitive', 'Complete the relation so that it is Euclidean but not transitive.', { minimumWorlds: 3, maximumWorlds: 3, maximumEdges: 5, requiredEdges: [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w1' }], forbiddenEdges: [{ from: 'w0', to: 'w2' }], requiredProperties: ['euclidean'], forbiddenProperties: ['transitive'] }, { worlds: [world('w0', '', 70, 130), world('w1', '', 300, 55), world('w2', '', 300, 205)], edges: [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }, { from: 'w1', to: 'w2' }, { from: 'w2', to: 'w1' }, { from: 'w2', to: 'w2' }], evaluationWorld: 'w0' }, ['Transitivity follows a chain x → y → z.', 'Euclideanity compares two successors of the same source.', 'Complete the successor cluster formed by w1 and w2 while leaving w0 → w2 absent.'], 'The engine uses xRy and xRz to require yRz.', 'The successor cluster is Euclidean, while w0 → w1 → w2 still lacks w0 → w2.'),
    frame([world('w0', '', 100, 130), world('w1', '', 390, 130)], [], 'architect-s4-style', 'S4-Style Frame', 'Construct a reflexive and transitive frame that is not symmetric.', { minimumWorlds: 2, maximumWorlds: 2, minimumEdges: 3, maximumEdges: 3, requiredProperties: ['reflexive', 'transitive'], forbiddenProperties: ['symmetric'] }, { worlds: [world('w0', '', 100, 130), world('w1', '', 390, 130)], edges: [{ from: 'w0', to: 'w0' }, { from: 'w1', to: 'w1' }, { from: 'w0', to: 'w1' }], evaluationWorld: 'w0' }, ['Begin by adding both required self-loops.', 'Add a one-way edge between the worlds.', 'Do not add its reverse.'], 'This mission constructs a preorder, not a complete modal-system classification.', 'The frame is reflexive and transitive, but not symmetric because accessibility runs from w0 to w1 but not back.'),
    frame([world('w0', '', 60, 130), world('w1', '', 270, 55), world('w2', '', 270, 205)], [{ from: 'w0', to: 'w0' }, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }, { from: 'w0', to: 'w1' }], 'architect-final-architecture', 'Final Architecture', 'Transform this preorder into a non-trivial equivalence relation by adding or removing as few explicit edges as possible.', { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 5, maximumEdges: 5, requiredProperties: ['reflexive', 'symmetric', 'transitive'] }, { worlds: [world('w0', '', 60, 130), world('w1', '', 270, 55), world('w2', '', 270, 205)], edges: [{ from: 'w0', to: 'w0' }, { from: 'w1', to: 'w1' }, { from: 'w2', to: 'w2' }, { from: 'w0', to: 'w1' }, { from: 'w1', to: 'w0' }], evaluationWorld: 'w0' }, ['An equivalence relation is reflexive, symmetric, and transitive.', 'Inspect every one-way edge left from the preorder.', 'Add the missing reverse edge and verify the whole relation.'], 'The starting frame is Stage A: reflexive and transitive but not symmetric.', 'Adding w1 → w0 turns the non-trivial preorder into an equivalence relation with classes {w0,w1} and {w2}.'),
  ],
}

const comparison = (id: string, title: string, formula: string, comparisonFormula: string, worlds: readonly ReturnType<typeof world>[], edges: readonly { readonly from: string; readonly to: string }[], comparisonTarget: NonNullable<GameLevel['comparisonTarget']>, instruction: string, hints: readonly [string, string, string], referenceSolution: NonNullable<GameLevel['referenceSolution']>, briefing: string, successDebrief: string, constraints?: GameLevel['constraints']): GameLevel => ({ id, chapter: 'Formula Laboratory', title, concept: 'Semantic formula comparison', learningObjective: instruction, briefing, instruction, formula, comparisonFormula, comparisonTarget, scope: 'pointed', targetTruth: false, evaluationWorld: 'w0', worlds, edges, constraints, editable: ['valuations', 'edges'], hints, successDebrief, targetAnalysis: ['Formula A and Formula B have stable labels throughout the mission.', `Goal: Formula A ${comparisonTarget.formulaATruth ? 'true' : 'false'}. Formula B ${comparisonTarget.formulaBTruth ? 'true' : 'false'} at w0.`], referenceSolution })
const twoBranch = () => [world('w0', '', 70, 130), world('w1', '', 310, 55), world('w2', '', 310, 205)]
const twoBranchEdges = [{ from: 'w0', to: 'w1' }, { from: 'w0', to: 'w2' }]

const formulaLaboratory: GuidedCampaign = {
  id: 'formula-laboratory', title: 'Formula Laboratory', description: 'Compare modal formulas, construct distinguishing models, and investigate when implication or equivalence succeeds.', difficulty: 'Intermediate–Advanced', completionInsight: 'Agreement in one model is not general equivalence. Formula relationships are established by their semantic clauses or refuted by a correctly scoped distinguishing model.',
  levels: [
    comparison('laboratory-possibility-duality', 'Possibility Duality', 'diamond p', '!box !p', [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], [{ from: 'w0', to: 'w1' }], { formulaATruth: true, formulaBTruth: true }, 'Verify that ◇p and ¬□¬p agree in an editable model.', ['Compare the existential claim with the negation of a universal counterexample claim.', 'Ask whether every successor fails p.', 'Use an accessible p-world to make both formulas true.'], { worlds: [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], edges: [{ from: 'w0', to: 'w1' }], evaluationWorld: 'w0' }, 'The examples illustrate a semantic duality. testing one model alone is not a proof.', '◇p and ¬□¬p agree by the modal semantic clauses: some p-successor exists exactly when not every successor is non-p.'),
    comparison('laboratory-necessity-duality', 'Necessity Duality', 'box p', '!diamond !p', [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], [{ from: 'w0', to: 'w1' }], { formulaATruth: true, formulaBTruth: true }, 'Verify that □p and ¬◇¬p agree in an editable model.', ['A box fails precisely when an accessible counterexample exists.', 'Look for a successor where p is false.', 'With only p-successors, both formulas are true.'], { worlds: [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], edges: [{ from: 'w0', to: 'w1' }], evaluationWorld: 'w0' }, 'Necessity means no accessible counterexample to p exists.', '□p and ¬◇¬p remain equivalent even at dead ends, where □p is vacuously true.'),
    comparison('laboratory-box-conjunction', 'Box and Conjunction', 'box (p & q)', '(box p & box q)', [world('w0', '', 100, 130), world('w1', 'p q', 390, 130)], [{ from: 'w0', to: 'w1' }], { formulaATruth: true, formulaBTruth: true }, 'Confirm that □(p ∧ q) and □p ∧ □q agree in this model.', ['A box quantifies over every successor.', 'Every successor must satisfy both p and q for Formula A.', 'Give every successor both atoms.'], { worlds: [world('w0', '', 100, 130), world('w1', 'p q', 390, 130)], edges: [{ from: 'w0', to: 'w1' }], evaluationWorld: 'w0' }, 'Universal quantification distributes over conjunction.', 'Every successor satisfies both conditions exactly when each condition holds at every successor.'),
    comparison('laboratory-diamond-disjunction', 'Diamond and Disjunction', 'diamond (p | q)', '(diamond p | diamond q)', [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], [{ from: 'w0', to: 'w1' }], { formulaATruth: true, formulaBTruth: true }, 'Confirm that ◇(p ∨ q) and ◇p ∨ ◇q agree in this model.', ['A diamond needs one successful successor.', 'That successor may satisfy either disjunct.', 'Use a p-world or a q-world as the witness.'], { worlds: [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], edges: [{ from: 'w0', to: 'w1' }], evaluationWorld: 'w0' }, 'Existential quantification distributes over disjunction.', 'One witness for p ∨ q is already a witness for one of its disjuncts.'),
    comparison('laboratory-failed-box-distribution', 'Failed Box Distribution', 'box (p | q)', '(box p | box q)', twoBranch(), twoBranchEdges, { formulaATruth: true, formulaBTruth: false }, 'Make Formula A true and Formula B false at w0.', ['Formula B is false only when both boxes are false.', 'Use one successor that falsifies p and another that falsifies q.', 'Put only p at one successor and only q at the other.'], { worlds: [world('w0', '', 70, 130), world('w1', 'p', 310, 55), world('w2', 'q', 310, 205)], edges: twoBranchEdges, evaluationWorld: 'w0' }, 'Every successor satisfies the disjunction, but no single disjunct is true throughout all successors.', 'Formula A distinguishes the formulas from Formula B and refutes A → B on arbitrary frames.', { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredEdges: twoBranchEdges }),
    comparison('laboratory-separate-diamond-witnesses', 'Separate Diamond Witnesses', 'diamond (p & q)', '(diamond p & diamond q)', twoBranch(), twoBranchEdges, { formulaATruth: false, formulaBTruth: true }, 'Make Formula B true and Formula A false at w0.', ['Formula B may use different witnesses for its two diamonds.', 'Keep p and q in separate successors.', 'Ensure no accessible world contains both atoms.'], { worlds: [world('w0', '', 70, 130), world('w1', 'p', 310, 55), world('w2', 'q', 310, 205)], edges: twoBranchEdges, evaluationWorld: 'w0' }, 'Two existential claims can use separate witnesses. a diamond over a conjunction needs one shared witness.', 'Formula B distinguishes the formulas from Formula A and refutes B → A on arbitrary frames.', { minimumWorlds: 3, maximumWorlds: 3, minimumEdges: 2, maximumEdges: 2, requiredEdges: twoBranchEdges }),
    comparison('laboratory-modal-order', 'Modal Order', 'box diamond p', 'diamond box p', [world('w0', '', 50, 130), world('w1', '', 220, 45), world('w2', '', 220, 215), world('w3', 'p', 430, 45), world('w4', '', 430, 215)], [{ from: 'w0', to: 'w1' }, { from: 'w0', to: 'w2' }, { from: 'w1', to: 'w3' }, { from: 'w1', to: 'w4' }, { from: 'w2', to: 'w3' }, { from: 'w2', to: 'w4' }], { formulaATruth: true, formulaBTruth: false }, 'Construct a model where □◇p is true and ◇□p is false.', ['Formula A asks every immediate successor for some p-option.', 'Formula B needs one immediate successor whose every option is a p-world.', 'Give each branch one p-option and one non-p option.'], { worlds: [world('w0', '', 50, 130), world('w1', '', 220, 45), world('w2', '', 220, 215), world('w3', 'p', 430, 45), world('w4', '', 430, 215)], edges: [{ from: 'w0', to: 'w1' }, { from: 'w0', to: 'w2' }, { from: 'w1', to: 'w3' }, { from: 'w1', to: 'w4' }, { from: 'w2', to: 'w3' }, { from: 'w2', to: 'w4' }], evaluationWorld: 'w0' }, 'Different modal orders place universal and existential quantification in different positions.', 'Every branch has a p-option, but no branch makes p necessary. Formula A is true and Formula B false.', { minimumWorlds: 5, maximumWorlds: 5, minimumEdges: 6, maximumEdges: 6 }),
    comparison('laboratory-frame-dependent', 'Frame-Dependent Implication', 'box p', 'diamond p', [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }], { formulaATruth: true, formulaBTruth: true }, 'Verify the serial-frame instance where □p entails ◇p.', ['On a serial frame, every world has at least one successor.', 'If p holds at every successor, at least one p-successor exists.', 'Keep the relation serial and make every successor of w0 satisfy p.'], { worlds: [world('w0', '', 100, 130), world('w1', 'p', 390, 130)], edges: [{ from: 'w0', to: 'w1' }, { from: 'w1', to: 'w1' }], evaluationWorld: 'w0' }, 'Seriality supplies the successor needed to turn □p into ◇p.', 'On serial frames, □p → ◇p is valid. Without seriality, a dead end refutes that implication.', { minimumWorlds: 2, maximumWorlds: 2, minimumEdges: 2, maximumEdges: 2, requiredProperties: ['serial'] }),
  ],
}

export const guidedCampaigns: readonly GuidedCampaign[] = [countermodelHunter, frameArchitect, formulaLaboratory]
